('Official 2 Con 1', 'TOEFL TPO 2 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/2-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 2 Lec 1', 'TOEFL TPO 2 Official Listening Practice - Astronomy', 'https://liuxue.koolearn.com/toefl/listen/2-2-q0.html', 'tpo_official', '中', 'Astronomy', 300, NOW()),
('Official 2 Lec 2', 'TOEFL TPO 2 Official Listening Practice - Archaeology', 'https://liuxue.koolearn.com/toefl/listen/2-3-q0.html', 'tpo_official', '中', 'Archaeology', 300, NOW()),
('Official 2 Con 2', 'TOEFL TPO 2 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/2-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 2 Lec 3', 'TOEFL TPO 2 Official Listening Practice - Chemistry', 'https://liuxue.koolearn.com/toefl/listen/2-5-q0.html', 'tpo_official', '中', 'Chemistry', 300, NOW()),
('Official 2 Lec 4', 'TOEFL TPO 2 Official Listening Practice - Music', 'https://liuxue.koolearn.com/toefl/listen/2-6-q0.html', 'tpo_official', '中', 'Music', 300, NOW()),
('Official 3 Con 1', 'TOEFL TPO 3 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/3-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 3 Lec 1', 'TOEFL TPO 3 Official Listening Practice - Chemistry', 'https://liuxue.koolearn.com/toefl/listen/3-2-q0.html', 'tpo_official', '中', 'Chemistry', 300, NOW()),
('Official 3 Lec 2', 'TOEFL TPO 3 Official Listening Practice - Music', 'https://liuxue.koolearn.com/toefl/listen/3-3-q0.html', 'tpo_official', '中', 'Music', 300, NOW()),
('Official 3 Con 2', 'TOEFL TPO 3 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/3-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 3 Lec 3', 'TOEFL TPO 3 Official Listening Practice - Philosophy', 'https://liuxue.koolearn.com/toefl/listen/3-5-q0.html', 'tpo_official', '中', 'Philosophy', 300, NOW()),
('Official 3 Lec 4', 'TOEFL TPO 3 Official Listening Practice - Anthropology', 'https://liuxue.koolearn.com/toefl/listen/3-6-q0.html', 'tpo_official', '中', 'Anthropology', 300, NOW()),
('Official 4 Con 1', 'TOEFL TPO 4 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/4-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 4 Lec 1', 'TOEFL TPO 4 Official Listening Practice - Literature', 'https://liuxue.koolearn.com/toefl/listen/4-2-q0.html', 'tpo_official', '中', 'Literature', 300, NOW()),
('Official 4 Lec 2', 'TOEFL TPO 4 Official Listening Practice - Philosophy', 'https://liuxue.koolearn.com/toefl/listen/4-3-q0.html', 'tpo_official', '中', 'Philosophy', 300, NOW()),
('Official 4 Con 2', 'TOEFL TPO 4 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/4-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 4 Lec 3', 'TOEFL TPO 4 Official Listening Practice - Business', 'https://liuxue.koolearn.com/toefl/listen/4-5-q0.html', 'tpo_official', '中', 'Business', 300, NOW()),
('Official 4 Lec 4', 'TOEFL TPO 4 Official Listening Practice - History', 'https://liuxue.koolearn.com/toefl/listen/4-6-q0.html', 'tpo_official', '中', 'History', 300, NOW()),
('Official 5 Con 1', 'TOEFL TPO 5 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/5-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 5 Lec 1', 'TOEFL TPO 5 Official Listening Practice - Anthropology', 'https://liuxue.koolearn.com/toefl/listen/5-2-q0.html', 'tpo_official', '中', 'Anthropology', 300, NOW()),
('Official 5 Lec 2', 'TOEFL TPO 5 Official Listening Practice - Geology', 'https://liuxue.koolearn.com/toefl/listen/5-3-q0.html', 'tpo_official', '中', 'Geology', 300, NOW()),
('Official 5 Con 2', 'TOEFL TPO 5 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/5-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 5 Lec 3', 'TOEFL TPO 5 Official Listening Practice - Physics', 'https://liuxue.koolearn.com/toefl/listen/5-5-q0.html', 'tpo_official', '中', 'Physics', 300, NOW()),
('Official 5 Lec 4', 'TOEFL TPO 5 Official Listening Practice - Sociology', 'https://liuxue.koolearn.com/toefl/listen/5-6-q0.html', 'tpo_official', '中', 'Sociology', 300, NOW()),
('Official 6 Con 1', 'TOEFL TPO 6 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/6-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 6 Lec 1', 'TOEFL TPO 6 Official Listening Practice - Business', 'https://liuxue.koolearn.com/toefl/listen/6-2-q0.html', 'tpo_official', '中', 'Business', 300, NOW()),
('Official 6 Lec 2', 'TOEFL TPO 6 Official Listening Practice - History', 'https://liuxue.koolearn.com/toefl/listen/6-3-q0.html', 'tpo_official', '中', 'History', 300, NOW()),
('Official 6 Con 2', 'TOEFL TPO 6 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/6-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 6 Lec 3', 'TOEFL TPO 6 Official Listening Practice - Economics', 'https://liuxue.koolearn.com/toefl/listen/6-5-q0.html', 'tpo_official', '中', 'Economics', 300, NOW()),
('Official 6 Lec 4', 'TOEFL TPO 6 Official Listening Practice - Architecture', 'https://liuxue.koolearn.com/toefl/listen/6-6-q0.html', 'tpo_official', '中', 'Architecture', 300, NOW()),
('Official 7 Con 1', 'TOEFL TPO 7 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/7-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 7 Lec 1', 'TOEFL TPO 7 Official Listening Practice - Engineering', 'https://liuxue.koolearn.com/toefl/listen/7-2-q0.html', 'tpo_official', '中', 'Engineering', 300, NOW()),
('Official 7 Lec 2', 'TOEFL TPO 7 Official Listening Practice - Physics', 'https://liuxue.koolearn.com/toefl/listen/7-3-q0.html', 'tpo_official', '中', 'Physics', 300, NOW()),
('Official 7 Con 2', 'TOEFL TPO 7 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/7-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 7 Lec 3', 'TOEFL TPO 7 Official Listening Practice - Political Science', 'https://liuxue.koolearn.com/toefl/listen/7-5-q0.html', 'tpo_official', '中', 'Political Science', 300, NOW()),
('Official 7 Lec 4', 'TOEFL TPO 7 Official Listening Practice - Mathematics', 'https://liuxue.koolearn.com/toefl/listen/7-6-q0.html', 'tpo_official', '中', 'Mathematics', 300, NOW()),
('Official 8 Con 1', 'TOEFL TPO 8 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/8-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 8 Lec 1', 'TOEFL TPO 8 Official Listening Practice - Sociology', 'https://liuxue.koolearn.com/toefl/listen/8-2-q0.html', 'tpo_official', '中', 'Sociology', 300, NOW()),
('Official 8 Lec 2', 'TOEFL TPO 8 Official Listening Practice - Linguistics', 'https://liuxue.koolearn.com/toefl/listen/8-3-q0.html', 'tpo_official', '中', 'Linguistics', 300, NOW()),
('Official 8 Con 2', 'TOEFL TPO 8 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/8-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 8 Lec 3', 'TOEFL TPO 8 Official Listening Practice - Medicine', 'https://liuxue.koolearn.com/toefl/listen/8-5-q0.html', 'tpo_official', '中', 'Medicine', 300, NOW()),
('Official 8 Lec 4', 'TOEFL TPO 8 Official Listening Practice - Agriculture', 'https://liuxue.koolearn.com/toefl/listen/8-6-q0.html', 'tpo_official', '中', 'Agriculture', 300, NOW()),
('Official 9 Con 1', 'TOEFL TPO 9 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/9-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 9 Lec 1', 'TOEFL TPO 9 Official Listening Practice - Economics', 'https://liuxue.koolearn.com/toefl/listen/9-2-q0.html', 'tpo_official', '中', 'Economics', 300, NOW()),
('Official 9 Lec 2', 'TOEFL TPO 9 Official Listening Practice - Architecture', 'https://liuxue.koolearn.com/toefl/listen/9-3-q0.html', 'tpo_official', '中', 'Architecture', 300, NOW()),
('Official 9 Con 2', 'TOEFL TPO 9 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/9-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 9 Lec 3', 'TOEFL TPO 9 Official Listening Practice - Biology', 'https://liuxue.koolearn.com/toefl/listen/9-5-q0.html', 'tpo_official', '中', 'Biology', 300, NOW()),
('Official 9 Lec 4', 'TOEFL TPO 9 Official Listening Practice - Art History', 'https://liuxue.koolearn.com/toefl/listen/9-6-q0.html', 'tpo_official', '中', 'Art History', 300, NOW()),
('Official 10 Con 1', 'TOEFL TPO 10 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/10-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 10 Lec 1', 'TOEFL TPO 10 Official Listening Practice - Geography', 'https://liuxue.koolearn.com/toefl/listen/10-2-q0.html', 'tpo_official', '中', 'Geography', 300, NOW()),
('Official 10 Lec 2', 'TOEFL TPO 10 Official Listening Practice - Political Science', 'https://liuxue.koolearn.com/toefl/listen/10-3-q0.html', 'tpo_official', '中', 'Political Science', 300, NOW()),
('Official 10 Con 2', 'TOEFL TPO 10 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/10-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 10 Lec 3', 'TOEFL TPO 10 Official Listening Practice - Psychology', 'https://liuxue.koolearn.com/toefl/listen/10-5-q0.html', 'tpo_official', '中', 'Psychology', 300, NOW()),
('Official 10 Lec 4', 'TOEFL TPO 10 Official Listening Practice - Astronomy', 'https://liuxue.koolearn.com/toefl/listen/10-6-q0.html', 'tpo_official', '中', 'Astronomy', 300, NOW()),
('Official 11 Con 1', 'TOEFL TPO 11 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/11-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 11 Lec 1', 'TOEFL TPO 11 Official Listening Practice - Mathematics', 'https://liuxue.koolearn.com/toefl/listen/11-2-q0.html', 'tpo_official', '中', 'Mathematics', 300, NOW()),
('Official 11 Lec 2', 'TOEFL TPO 11 Official Listening Practice - Computer Science', 'https://liuxue.koolearn.com/toefl/listen/11-3-q0.html', 'tpo_official', '中', 'Computer Science', 300, NOW()),
('Official 11 Con 2', 'TOEFL TPO 11 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/11-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 11 Lec 3', 'TOEFL TPO 11 Official Listening Practice - Chemistry', 'https://liuxue.koolearn.com/toefl/listen/11-5-q0.html', 'tpo_official', '中', 'Chemistry', 300, NOW()),
('Official 11 Lec 4', 'TOEFL TPO 11 Official Listening Practice - Music', 'https://liuxue.koolearn.com/toefl/listen/11-6-q0.html', 'tpo_official', '中', 'Music', 300, NOW()),
('Official 12 Con 1', 'TOEFL TPO 12 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/12-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 12 Lec 1', 'TOEFL TPO 12 Official Listening Practice - Medicine', 'https://liuxue.koolearn.com/toefl/listen/12-2-q0.html', 'tpo_official', '中', 'Medicine', 300, NOW()),
('Official 12 Lec 2', 'TOEFL TPO 12 Official Listening Practice - Agriculture', 'https://liuxue.koolearn.com/toefl/listen/12-3-q0.html', 'tpo_official', '中', 'Agriculture', 300, NOW()),
('Official 12 Con 2', 'TOEFL TPO 12 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/12-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 12 Lec 3', 'TOEFL TPO 12 Official Listening Practice - Philosophy', 'https://liuxue.koolearn.com/toefl/listen/12-5-q0.html', 'tpo_official', '中', 'Philosophy', 300, NOW()),
('Official 12 Lec 4', 'TOEFL TPO 12 Official Listening Practice - Anthropology', 'https://liuxue.koolearn.com/toefl/listen/12-6-q0.html', 'tpo_official', '中', 'Anthropology', 300, NOW()),
('Official 13 Con 1', 'TOEFL TPO 13 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/13-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 13 Lec 1', 'TOEFL TPO 13 Official Listening Practice - Journalism', 'https://liuxue.koolearn.com/toefl/listen/13-2-q0.html', 'tpo_official', '中', 'Journalism', 300, NOW()),
('Official 13 Lec 2', 'TOEFL TPO 13 Official Listening Practice - Biology', 'https://liuxue.koolearn.com/toefl/listen/13-3-q0.html', 'tpo_official', '中', 'Biology', 300, NOW()),
('Official 13 Con 2', 'TOEFL TPO 13 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/13-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 13 Lec 3', 'TOEFL TPO 13 Official Listening Practice - Business', 'https://liuxue.koolearn.com/toefl/listen/13-5-q0.html', 'tpo_official', '中', 'Business', 300, NOW()),
('Official 13 Lec 4', 'TOEFL TPO 13 Official Listening Practice - History', 'https://liuxue.koolearn.com/toefl/listen/13-6-q0.html', 'tpo_official', '中', 'History', 300, NOW()),
('Official 14 Con 1', 'TOEFL TPO 14 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/14-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 14 Lec 1', 'TOEFL TPO 14 Official Listening Practice - Art History', 'https://liuxue.koolearn.com/toefl/listen/14-2-q0.html', 'tpo_official', '中', 'Art History', 300, NOW()),
('Official 14 Lec 2', 'TOEFL TPO 14 Official Listening Practice - Environmental Science', 'https://liuxue.koolearn.com/toefl/listen/14-3-q0.html', 'tpo_official', '中', 'Environmental Science', 300, NOW()),
('Official 14 Con 2', 'TOEFL TPO 14 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/14-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 14 Lec 3', 'TOEFL TPO 14 Official Listening Practice - Physics', 'https://liuxue.koolearn.com/toefl/listen/14-5-q0.html', 'tpo_official', '中', 'Physics', 300, NOW()),
('Official 14 Lec 4', 'TOEFL TPO 14 Official Listening Practice - Sociology', 'https://liuxue.koolearn.com/toefl/listen/14-6-q0.html', 'tpo_official', '中', 'Sociology', 300, NOW()),
('Official 15 Con 1', 'TOEFL TPO 15 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/15-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 15 Lec 1', 'TOEFL TPO 15 Official Listening Practice - Psychology', 'https://liuxue.koolearn.com/toefl/listen/15-2-q0.html', 'tpo_official', '中', 'Psychology', 300, NOW()),
('Official 15 Lec 2', 'TOEFL TPO 15 Official Listening Practice - Astronomy', 'https://liuxue.koolearn.com/toefl/listen/15-3-q0.html', 'tpo_official', '中', 'Astronomy', 300, NOW()),
('Official 15 Con 2', 'TOEFL TPO 15 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/15-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 15 Lec 3', 'TOEFL TPO 15 Official Listening Practice - Economics', 'https://liuxue.koolearn.com/toefl/listen/15-5-q0.html', 'tpo_official', '中', 'Economics', 300, NOW()),
('Official 15 Lec 4', 'TOEFL TPO 15 Official Listening Practice - Architecture', 'https://liuxue.koolearn.com/toefl/listen/15-6-q0.html', 'tpo_official', '中', 'Architecture', 300, NOW()),
('Official 16 Con 1', 'TOEFL TPO 16 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/16-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 16 Lec 1', 'TOEFL TPO 16 Official Listening Practice - Archaeology', 'https://liuxue.koolearn.com/toefl/listen/16-2-q0.html', 'tpo_official', '中', 'Archaeology', 300, NOW()),
('Official 16 Lec 2', 'TOEFL TPO 16 Official Listening Practice - Chemistry', 'https://liuxue.koolearn.com/toefl/listen/16-3-q0.html', 'tpo_official', '中', 'Chemistry', 300, NOW()),
('Official 16 Con 2', 'TOEFL TPO 16 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/16-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 16 Lec 3', 'TOEFL TPO 16 Official Listening Practice - Political Science', 'https://liuxue.koolearn.com/toefl/listen/16-5-q0.html', 'tpo_official', '中', 'Political Science', 300, NOW()),
('Official 16 Lec 4', 'TOEFL TPO 16 Official Listening Practice - Mathematics', 'https://liuxue.koolearn.com/toefl/listen/16-6-q0.html', 'tpo_official', '中', 'Mathematics', 300, NOW()),
('Official 17 Con 1', 'TOEFL TPO 17 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/17-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 17 Lec 1', 'TOEFL TPO 17 Official Listening Practice - Music', 'https://liuxue.koolearn.com/toefl/listen/17-2-q0.html', 'tpo_official', '中', 'Music', 300, NOW()),
('Official 17 Lec 2', 'TOEFL TPO 17 Official Listening Practice - Literature', 'https://liuxue.koolearn.com/toefl/listen/17-3-q0.html', 'tpo_official', '中', 'Literature', 300, NOW()),
('Official 17 Con 2', 'TOEFL TPO 17 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/17-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 17 Lec 3', 'TOEFL TPO 17 Official Listening Practice - Medicine', 'https://liuxue.koolearn.com/toefl/listen/17-5-q0.html', 'tpo_official', '中', 'Medicine', 300, NOW()),
('Official 17 Lec 4', 'TOEFL TPO 17 Official Listening Practice - Agriculture', 'https://liuxue.koolearn.com/toefl/listen/17-6-q0.html', 'tpo_official', '中', 'Agriculture', 300, NOW()),
('Official 18 Con 1', 'TOEFL TPO 18 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/18-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 18 Lec 1', 'TOEFL TPO 18 Official Listening Practice - Philosophy', 'https://liuxue.koolearn.com/toefl/listen/18-2-q0.html', 'tpo_official', '中', 'Philosophy', 300, NOW()),
('Official 18 Lec 2', 'TOEFL TPO 18 Official Listening Practice - Anthropology', 'https://liuxue.koolearn.com/toefl/listen/18-3-q0.html', 'tpo_official', '中', 'Anthropology', 300, NOW()),
('Official 18 Con 2', 'TOEFL TPO 18 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/18-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
;
