-- TPO 2-64 批量插入語句

INSERT INTO content_source (name, description, url, type, difficulty_level, topic, duration, created_at) VALUES
('Official 2 Con 1', 'TOEFL TPO 2 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/2-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 2 Lec 1', 'TOEFL TPO 2 Official Listening Practice - Astronomy', 'https://liuxue.koolearn.com/toefl/listen/2-2-q0.html', 'tpo_official', '中', 'Astronomy', 300, NOW()),
('Official 2 Lec 2', 'TOEFL TPO 2 Official Listening Practice - Archaeology', 'https://liuxue.koolearn.com/toefl/listen/2-3-q0.html', 'tpo_official', '中', 'Archaeology', 300, NOW()),
('Official 2 Con 2', 'TOEFL TPO 2 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/2-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 2 Lec 3', 'TOEFL TPO 2 Official Listening Practice - Chemistry', 'https://liuxue.koolearn.com/toefl/listen/2-5-q0.html', 'tpo_official', '中', 'Chemistry', 300, NOW()),
('Official 2 Lec 4', 'TOEFL TPO 2 Official Listening Practice - Music', 'https://liuxue.koolearn.com/toefl/listen/2-6-q0.html', 'tpo_official', '中', 'Music', 300, NOW()),
('Official 3 Con 1', 'TOEFL TPO 3 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/3-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 3 Lec 1', 'TOEFL TPO 3 Official Listening Practice - Chemistry', 'https://liuxue.koolearn.com/toefl/listen/3-2-q0.html', 'tpo_official', '中', 'Chemistry', 300, NOW()),
('Official 3 Lec 2', 'TOEFL TPO 3 Official Listening Practice - Music', 'https://liuxue.koolearn.com/toefl/listen/3-3-q0.html', 'tpo_official', '中', 'Music', 300, NOW()),
('Official 3 Con 2', 'TOEFL TPO 3 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/3-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 3 Lec 3', 'TOEFL TPO 3 Official Listening Practice - Philosophy', 'https://liuxue.koolearn.com/toefl/listen/3-5-q0.html', 'tpo_official', '中', 'Philosophy', 300, NOW()),
('Official 3 Lec 4', 'TOEFL TPO 3 Official Listening Practice - Anthropology', 'https://liuxue.koolearn.com/toefl/listen/3-6-q0.html', 'tpo_official', '中', 'Anthropology', 300, NOW()),
('Official 4 Con 1', 'TOEFL TPO 4 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/4-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 4 Lec 1', 'TOEFL TPO 4 Official Listening Practice - Literature', 'https://liuxue.koolearn.com/toefl/listen/4-2-q0.html', 'tpo_official', '中', 'Literature', 300, NOW()),
('Official 4 Lec 2', 'TOEFL TPO 4 Official Listening Practice - Philosophy', 'https://liuxue.koolearn.com/toefl/listen/4-3-q0.html', 'tpo_official', '中', 'Philosophy', 300, NOW()),
('Official 4 Con 2', 'TOEFL TPO 4 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/4-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 4 Lec 3', 'TOEFL TPO 4 Official Listening Practice - Business', 'https://liuxue.koolearn.com/toefl/listen/4-5-q0.html', 'tpo_official', '中', 'Business', 300, NOW()),
('Official 4 Lec 4', 'TOEFL TPO 4 Official Listening Practice - History', 'https://liuxue.koolearn.com/toefl/listen/4-6-q0.html', 'tpo_official', '中', 'History', 300, NOW()),
('Official 5 Con 1', 'TOEFL TPO 5 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/5-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 5 Lec 1', 'TOEFL TPO 5 Official Listening Practice - Anthropology', 'https://liuxue.koolearn.com/toefl/listen/5-2-q0.html', 'tpo_official', '中', 'Anthropology', 300, NOW()),
('Official 5 Lec 2', 'TOEFL TPO 5 Official Listening Practice - Geology', 'https://liuxue.koolearn.com/toefl/listen/5-3-q0.html', 'tpo_official', '中', 'Geology', 300, NOW()),
('Official 5 Con 2', 'TOEFL TPO 5 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/5-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 5 Lec 3', 'TOEFL TPO 5 Official Listening Practice - Physics', 'https://liuxue.koolearn.com/toefl/listen/5-5-q0.html', 'tpo_official', '中', 'Physics', 300, NOW()),
('Official 5 Lec 4', 'TOEFL TPO 5 Official Listening Practice - Sociology', 'https://liuxue.koolearn.com/toefl/listen/5-6-q0.html', 'tpo_official', '中', 'Sociology', 300, NOW()),
('Official 6 Con 1', 'TOEFL TPO 6 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/6-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 6 Lec 1', 'TOEFL TPO 6 Official Listening Practice - Business', 'https://liuxue.koolearn.com/toefl/listen/6-2-q0.html', 'tpo_official', '中', 'Business', 300, NOW()),
('Official 6 Lec 2', 'TOEFL TPO 6 Official Listening Practice - History', 'https://liuxue.koolearn.com/toefl/listen/6-3-q0.html', 'tpo_official', '中', 'History', 300, NOW()),
('Official 6 Con 2', 'TOEFL TPO 6 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/6-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 6 Lec 3', 'TOEFL TPO 6 Official Listening Practice - Economics', 'https://liuxue.koolearn.com/toefl/listen/6-5-q0.html', 'tpo_official', '中', 'Economics', 300, NOW()),
('Official 6 Lec 4', 'TOEFL TPO 6 Official Listening Practice - Architecture', 'https://liuxue.koolearn.com/toefl/listen/6-6-q0.html', 'tpo_official', '中', 'Architecture', 300, NOW()),
('Official 7 Con 1', 'TOEFL TPO 7 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/7-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 7 Lec 1', 'TOEFL TPO 7 Official Listening Practice - Engineering', 'https://liuxue.koolearn.com/toefl/listen/7-2-q0.html', 'tpo_official', '中', 'Engineering', 300, NOW()),
('Official 7 Lec 2', 'TOEFL TPO 7 Official Listening Practice - Physics', 'https://liuxue.koolearn.com/toefl/listen/7-3-q0.html', 'tpo_official', '中', 'Physics', 300, NOW()),
('Official 7 Con 2', 'TOEFL TPO 7 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/7-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 7 Lec 3', 'TOEFL TPO 7 Official Listening Practice - Political Science', 'https://liuxue.koolearn.com/toefl/listen/7-5-q0.html', 'tpo_official', '中', 'Political Science', 300, NOW()),
('Official 7 Lec 4', 'TOEFL TPO 7 Official Listening Practice - Mathematics', 'https://liuxue.koolearn.com/toefl/listen/7-6-q0.html', 'tpo_official', '中', 'Mathematics', 300, NOW()),
('Official 8 Con 1', 'TOEFL TPO 8 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/8-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 8 Lec 1', 'TOEFL TPO 8 Official Listening Practice - Sociology', 'https://liuxue.koolearn.com/toefl/listen/8-2-q0.html', 'tpo_official', '中', 'Sociology', 300, NOW()),
('Official 8 Lec 2', 'TOEFL TPO 8 Official Listening Practice - Linguistics', 'https://liuxue.koolearn.com/toefl/listen/8-3-q0.html', 'tpo_official', '中', 'Linguistics', 300, NOW()),
('Official 8 Con 2', 'TOEFL TPO 8 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/8-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 8 Lec 3', 'TOEFL TPO 8 Official Listening Practice - Medicine', 'https://liuxue.koolearn.com/toefl/listen/8-5-q0.html', 'tpo_official', '中', 'Medicine', 300, NOW()),
('Official 8 Lec 4', 'TOEFL TPO 8 Official Listening Practice - Agriculture', 'https://liuxue.koolearn.com/toefl/listen/8-6-q0.html', 'tpo_official', '中', 'Agriculture', 300, NOW()),
('Official 9 Con 1', 'TOEFL TPO 9 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/9-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 9 Lec 1', 'TOEFL TPO 9 Official Listening Practice - Economics', 'https://liuxue.koolearn.com/toefl/listen/9-2-q0.html', 'tpo_official', '中', 'Economics', 300, NOW()),
('Official 9 Lec 2', 'TOEFL TPO 9 Official Listening Practice - Architecture', 'https://liuxue.koolearn.com/toefl/listen/9-3-q0.html', 'tpo_official', '中', 'Architecture', 300, NOW()),
('Official 9 Con 2', 'TOEFL TPO 9 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/9-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 9 Lec 3', 'TOEFL TPO 9 Official Listening Practice - Biology', 'https://liuxue.koolearn.com/toefl/listen/9-5-q0.html', 'tpo_official', '中', 'Biology', 300, NOW()),
('Official 9 Lec 4', 'TOEFL TPO 9 Official Listening Practice - Art History', 'https://liuxue.koolearn.com/toefl/listen/9-6-q0.html', 'tpo_official', '中', 'Art History', 300, NOW()),
('Official 10 Con 1', 'TOEFL TPO 10 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/10-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 10 Lec 1', 'TOEFL TPO 10 Official Listening Practice - Geography', 'https://liuxue.koolearn.com/toefl/listen/10-2-q0.html', 'tpo_official', '中', 'Geography', 300, NOW()),
('Official 10 Lec 2', 'TOEFL TPO 10 Official Listening Practice - Political Science', 'https://liuxue.koolearn.com/toefl/listen/10-3-q0.html', 'tpo_official', '中', 'Political Science', 300, NOW()),
('Official 10 Con 2', 'TOEFL TPO 10 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/10-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 10 Lec 3', 'TOEFL TPO 10 Official Listening Practice - Psychology', 'https://liuxue.koolearn.com/toefl/listen/10-5-q0.html', 'tpo_official', '中', 'Psychology', 300, NOW()),
('Official 10 Lec 4', 'TOEFL TPO 10 Official Listening Practice - Astronomy', 'https://liuxue.koolearn.com/toefl/listen/10-6-q0.html', 'tpo_official', '中', 'Astronomy', 300, NOW()),
('Official 11 Con 1', 'TOEFL TPO 11 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/11-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 11 Lec 1', 'TOEFL TPO 11 Official Listening Practice - Mathematics', 'https://liuxue.koolearn.com/toefl/listen/11-2-q0.html', 'tpo_official', '中', 'Mathematics', 300, NOW()),
('Official 11 Lec 2', 'TOEFL TPO 11 Official Listening Practice - Computer Science', 'https://liuxue.koolearn.com/toefl/listen/11-3-q0.html', 'tpo_official', '中', 'Computer Science', 300, NOW()),
('Official 11 Con 2', 'TOEFL TPO 11 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/11-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 11 Lec 3', 'TOEFL TPO 11 Official Listening Practice - Chemistry', 'https://liuxue.koolearn.com/toefl/listen/11-5-q0.html', 'tpo_official', '中', 'Chemistry', 300, NOW()),
('Official 11 Lec 4', 'TOEFL TPO 11 Official Listening Practice - Music', 'https://liuxue.koolearn.com/toefl/listen/11-6-q0.html', 'tpo_official', '中', 'Music', 300, NOW()),
('Official 12 Con 1', 'TOEFL TPO 12 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/12-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 12 Lec 1', 'TOEFL TPO 12 Official Listening Practice - Medicine', 'https://liuxue.koolearn.com/toefl/listen/12-2-q0.html', 'tpo_official', '中', 'Medicine', 300, NOW()),
('Official 12 Lec 2', 'TOEFL TPO 12 Official Listening Practice - Agriculture', 'https://liuxue.koolearn.com/toefl/listen/12-3-q0.html', 'tpo_official', '中', 'Agriculture', 300, NOW()),
('Official 12 Con 2', 'TOEFL TPO 12 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/12-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 12 Lec 3', 'TOEFL TPO 12 Official Listening Practice - Philosophy', 'https://liuxue.koolearn.com/toefl/listen/12-5-q0.html', 'tpo_official', '中', 'Philosophy', 300, NOW()),
('Official 12 Lec 4', 'TOEFL TPO 12 Official Listening Practice - Anthropology', 'https://liuxue.koolearn.com/toefl/listen/12-6-q0.html', 'tpo_official', '中', 'Anthropology', 300, NOW()),
('Official 13 Con 1', 'TOEFL TPO 13 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/13-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 13 Lec 1', 'TOEFL TPO 13 Official Listening Practice - Journalism', 'https://liuxue.koolearn.com/toefl/listen/13-2-q0.html', 'tpo_official', '中', 'Journalism', 300, NOW()),
('Official 13 Lec 2', 'TOEFL TPO 13 Official Listening Practice - Biology', 'https://liuxue.koolearn.com/toefl/listen/13-3-q0.html', 'tpo_official', '中', 'Biology', 300, NOW()),
('Official 13 Con 2', 'TOEFL TPO 13 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/13-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 13 Lec 3', 'TOEFL TPO 13 Official Listening Practice - Business', 'https://liuxue.koolearn.com/toefl/listen/13-5-q0.html', 'tpo_official', '中', 'Business', 300, NOW()),
('Official 13 Lec 4', 'TOEFL TPO 13 Official Listening Practice - History', 'https://liuxue.koolearn.com/toefl/listen/13-6-q0.html', 'tpo_official', '中', 'History', 300, NOW()),
('Official 14 Con 1', 'TOEFL TPO 14 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/14-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 14 Lec 1', 'TOEFL TPO 14 Official Listening Practice - Art History', 'https://liuxue.koolearn.com/toefl/listen/14-2-q0.html', 'tpo_official', '中', 'Art History', 300, NOW()),
('Official 14 Lec 2', 'TOEFL TPO 14 Official Listening Practice - Environmental Science', 'https://liuxue.koolearn.com/toefl/listen/14-3-q0.html', 'tpo_official', '中', 'Environmental Science', 300, NOW()),
('Official 14 Con 2', 'TOEFL TPO 14 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/14-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 14 Lec 3', 'TOEFL TPO 14 Official Listening Practice - Physics', 'https://liuxue.koolearn.com/toefl/listen/14-5-q0.html', 'tpo_official', '中', 'Physics', 300, NOW()),
('Official 14 Lec 4', 'TOEFL TPO 14 Official Listening Practice - Sociology', 'https://liuxue.koolearn.com/toefl/listen/14-6-q0.html', 'tpo_official', '中', 'Sociology', 300, NOW()),
('Official 15 Con 1', 'TOEFL TPO 15 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/15-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 15 Lec 1', 'TOEFL TPO 15 Official Listening Practice - Psychology', 'https://liuxue.koolearn.com/toefl/listen/15-2-q0.html', 'tpo_official', '中', 'Psychology', 300, NOW()),
('Official 15 Lec 2', 'TOEFL TPO 15 Official Listening Practice - Astronomy', 'https://liuxue.koolearn.com/toefl/listen/15-3-q0.html', 'tpo_official', '中', 'Astronomy', 300, NOW()),
('Official 15 Con 2', 'TOEFL TPO 15 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/15-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 15 Lec 3', 'TOEFL TPO 15 Official Listening Practice - Economics', 'https://liuxue.koolearn.com/toefl/listen/15-5-q0.html', 'tpo_official', '中', 'Economics', 300, NOW()),
('Official 15 Lec 4', 'TOEFL TPO 15 Official Listening Practice - Architecture', 'https://liuxue.koolearn.com/toefl/listen/15-6-q0.html', 'tpo_official', '中', 'Architecture', 300, NOW()),
('Official 16 Con 1', 'TOEFL TPO 16 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/16-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 16 Lec 1', 'TOEFL TPO 16 Official Listening Practice - Archaeology', 'https://liuxue.koolearn.com/toefl/listen/16-2-q0.html', 'tpo_official', '中', 'Archaeology', 300, NOW()),
('Official 16 Lec 2', 'TOEFL TPO 16 Official Listening Practice - Chemistry', 'https://liuxue.koolearn.com/toefl/listen/16-3-q0.html', 'tpo_official', '中', 'Chemistry', 300, NOW()),
('Official 16 Con 2', 'TOEFL TPO 16 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/16-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 16 Lec 3', 'TOEFL TPO 16 Official Listening Practice - Political Science', 'https://liuxue.koolearn.com/toefl/listen/16-5-q0.html', 'tpo_official', '中', 'Political Science', 300, NOW()),
('Official 16 Lec 4', 'TOEFL TPO 16 Official Listening Practice - Mathematics', 'https://liuxue.koolearn.com/toefl/listen/16-6-q0.html', 'tpo_official', '中', 'Mathematics', 300, NOW()),
('Official 17 Con 1', 'TOEFL TPO 17 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/17-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 17 Lec 1', 'TOEFL TPO 17 Official Listening Practice - Music', 'https://liuxue.koolearn.com/toefl/listen/17-2-q0.html', 'tpo_official', '中', 'Music', 300, NOW()),
('Official 17 Lec 2', 'TOEFL TPO 17 Official Listening Practice - Literature', 'https://liuxue.koolearn.com/toefl/listen/17-3-q0.html', 'tpo_official', '中', 'Literature', 300, NOW()),
('Official 17 Con 2', 'TOEFL TPO 17 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/17-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 17 Lec 3', 'TOEFL TPO 17 Official Listening Practice - Medicine', 'https://liuxue.koolearn.com/toefl/listen/17-5-q0.html', 'tpo_official', '中', 'Medicine', 300, NOW()),
('Official 17 Lec 4', 'TOEFL TPO 17 Official Listening Practice - Agriculture', 'https://liuxue.koolearn.com/toefl/listen/17-6-q0.html', 'tpo_official', '中', 'Agriculture', 300, NOW()),
('Official 18 Con 1', 'TOEFL TPO 18 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/18-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 18 Lec 1', 'TOEFL TPO 18 Official Listening Practice - Philosophy', 'https://liuxue.koolearn.com/toefl/listen/18-2-q0.html', 'tpo_official', '中', 'Philosophy', 300, NOW()),
('Official 18 Lec 2', 'TOEFL TPO 18 Official Listening Practice - Anthropology', 'https://liuxue.koolearn.com/toefl/listen/18-3-q0.html', 'tpo_official', '中', 'Anthropology', 300, NOW()),
('Official 18 Con 2', 'TOEFL TPO 18 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/18-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 18 Lec 3', 'TOEFL TPO 18 Official Listening Practice - Biology', 'https://liuxue.koolearn.com/toefl/listen/18-5-q0.html', 'tpo_official', '中', 'Biology', 300, NOW()),
('Official 18 Lec 4', 'TOEFL TPO 18 Official Listening Practice - Art History', 'https://liuxue.koolearn.com/toefl/listen/18-6-q0.html', 'tpo_official', '中', 'Art History', 300, NOW()),
('Official 19 Con 1', 'TOEFL TPO 19 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/19-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 19 Lec 1', 'TOEFL TPO 19 Official Listening Practice - Geology', 'https://liuxue.koolearn.com/toefl/listen/19-2-q0.html', 'tpo_official', '中', 'Geology', 300, NOW()),
('Official 19 Lec 2', 'TOEFL TPO 19 Official Listening Practice - Business', 'https://liuxue.koolearn.com/toefl/listen/19-3-q0.html', 'tpo_official', '中', 'Business', 300, NOW()),
('Official 19 Con 2', 'TOEFL TPO 19 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/19-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 19 Lec 3', 'TOEFL TPO 19 Official Listening Practice - Psychology', 'https://liuxue.koolearn.com/toefl/listen/19-5-q0.html', 'tpo_official', '中', 'Psychology', 300, NOW()),
('Official 19 Lec 4', 'TOEFL TPO 19 Official Listening Practice - Astronomy', 'https://liuxue.koolearn.com/toefl/listen/19-6-q0.html', 'tpo_official', '中', 'Astronomy', 300, NOW()),
('Official 20 Con 1', 'TOEFL TPO 20 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/20-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 20 Lec 1', 'TOEFL TPO 20 Official Listening Practice - History', 'https://liuxue.koolearn.com/toefl/listen/20-2-q0.html', 'tpo_official', '中', 'History', 300, NOW()),
('Official 20 Lec 2', 'TOEFL TPO 20 Official Listening Practice - Engineering', 'https://liuxue.koolearn.com/toefl/listen/20-3-q0.html', 'tpo_official', '中', 'Engineering', 300, NOW()),
('Official 20 Con 2', 'TOEFL TPO 20 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/20-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 20 Lec 3', 'TOEFL TPO 20 Official Listening Practice - Chemistry', 'https://liuxue.koolearn.com/toefl/listen/20-5-q0.html', 'tpo_official', '中', 'Chemistry', 300, NOW()),
('Official 20 Lec 4', 'TOEFL TPO 20 Official Listening Practice - Music', 'https://liuxue.koolearn.com/toefl/listen/20-6-q0.html', 'tpo_official', '中', 'Music', 300, NOW()),
('Official 21 Con 1', 'TOEFL TPO 21 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/21-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 21 Lec 1', 'TOEFL TPO 21 Official Listening Practice - Physics', 'https://liuxue.koolearn.com/toefl/listen/21-2-q0.html', 'tpo_official', '中', 'Physics', 300, NOW()),
('Official 21 Lec 2', 'TOEFL TPO 21 Official Listening Practice - Sociology', 'https://liuxue.koolearn.com/toefl/listen/21-3-q0.html', 'tpo_official', '中', 'Sociology', 300, NOW()),
('Official 21 Con 2', 'TOEFL TPO 21 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/21-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 21 Lec 3', 'TOEFL TPO 21 Official Listening Practice - Philosophy', 'https://liuxue.koolearn.com/toefl/listen/21-5-q0.html', 'tpo_official', '中', 'Philosophy', 300, NOW()),
('Official 21 Lec 4', 'TOEFL TPO 21 Official Listening Practice - Anthropology', 'https://liuxue.koolearn.com/toefl/listen/21-6-q0.html', 'tpo_official', '中', 'Anthropology', 300, NOW()),
('Official 22 Con 1', 'TOEFL TPO 22 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/22-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 22 Lec 1', 'TOEFL TPO 22 Official Listening Practice - Linguistics', 'https://liuxue.koolearn.com/toefl/listen/22-2-q0.html', 'tpo_official', '中', 'Linguistics', 300, NOW()),
('Official 22 Lec 2', 'TOEFL TPO 22 Official Listening Practice - Economics', 'https://liuxue.koolearn.com/toefl/listen/22-3-q0.html', 'tpo_official', '中', 'Economics', 300, NOW()),
('Official 22 Con 2', 'TOEFL TPO 22 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/22-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 22 Lec 3', 'TOEFL TPO 22 Official Listening Practice - Business', 'https://liuxue.koolearn.com/toefl/listen/22-5-q0.html', 'tpo_official', '中', 'Business', 300, NOW()),
('Official 22 Lec 4', 'TOEFL TPO 22 Official Listening Practice - History', 'https://liuxue.koolearn.com/toefl/listen/22-6-q0.html', 'tpo_official', '中', 'History', 300, NOW()),
('Official 23 Con 1', 'TOEFL TPO 23 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/23-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 23 Lec 1', 'TOEFL TPO 23 Official Listening Practice - Architecture', 'https://liuxue.koolearn.com/toefl/listen/23-2-q0.html', 'tpo_official', '中', 'Architecture', 300, NOW()),
('Official 23 Lec 2', 'TOEFL TPO 23 Official Listening Practice - Geography', 'https://liuxue.koolearn.com/toefl/listen/23-3-q0.html', 'tpo_official', '中', 'Geography', 300, NOW()),
('Official 23 Con 2', 'TOEFL TPO 23 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/23-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 23 Lec 3', 'TOEFL TPO 23 Official Listening Practice - Physics', 'https://liuxue.koolearn.com/toefl/listen/23-5-q0.html', 'tpo_official', '中', 'Physics', 300, NOW()),
('Official 23 Lec 4', 'TOEFL TPO 23 Official Listening Practice - Sociology', 'https://liuxue.koolearn.com/toefl/listen/23-6-q0.html', 'tpo_official', '中', 'Sociology', 300, NOW()),
('Official 24 Con 1', 'TOEFL TPO 24 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/24-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 24 Lec 1', 'TOEFL TPO 24 Official Listening Practice - Political Science', 'https://liuxue.koolearn.com/toefl/listen/24-2-q0.html', 'tpo_official', '中', 'Political Science', 300, NOW()),
('Official 24 Lec 2', 'TOEFL TPO 24 Official Listening Practice - Mathematics', 'https://liuxue.koolearn.com/toefl/listen/24-3-q0.html', 'tpo_official', '中', 'Mathematics', 300, NOW()),
('Official 24 Con 2', 'TOEFL TPO 24 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/24-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 24 Lec 3', 'TOEFL TPO 24 Official Listening Practice - Economics', 'https://liuxue.koolearn.com/toefl/listen/24-5-q0.html', 'tpo_official', '中', 'Economics', 300, NOW()),
('Official 24 Lec 4', 'TOEFL TPO 24 Official Listening Practice - Architecture', 'https://liuxue.koolearn.com/toefl/listen/24-6-q0.html', 'tpo_official', '中', 'Architecture', 300, NOW()),
('Official 25 Con 1', 'TOEFL TPO 25 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/25-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 25 Lec 1', 'TOEFL TPO 25 Official Listening Practice - Computer Science', 'https://liuxue.koolearn.com/toefl/listen/25-2-q0.html', 'tpo_official', '中', 'Computer Science', 300, NOW()),
('Official 25 Lec 2', 'TOEFL TPO 25 Official Listening Practice - Medicine', 'https://liuxue.koolearn.com/toefl/listen/25-3-q0.html', 'tpo_official', '中', 'Medicine', 300, NOW()),
('Official 25 Con 2', 'TOEFL TPO 25 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/25-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 25 Lec 3', 'TOEFL TPO 25 Official Listening Practice - Political Science', 'https://liuxue.koolearn.com/toefl/listen/25-5-q0.html', 'tpo_official', '中', 'Political Science', 300, NOW()),
('Official 25 Lec 4', 'TOEFL TPO 25 Official Listening Practice - Mathematics', 'https://liuxue.koolearn.com/toefl/listen/25-6-q0.html', 'tpo_official', '中', 'Mathematics', 300, NOW()),
('Official 26 Con 1', 'TOEFL TPO 26 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/26-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 26 Lec 1', 'TOEFL TPO 26 Official Listening Practice - Agriculture', 'https://liuxue.koolearn.com/toefl/listen/26-2-q0.html', 'tpo_official', '中', 'Agriculture', 300, NOW()),
('Official 26 Lec 2', 'TOEFL TPO 26 Official Listening Practice - Journalism', 'https://liuxue.koolearn.com/toefl/listen/26-3-q0.html', 'tpo_official', '中', 'Journalism', 300, NOW()),
('Official 26 Con 2', 'TOEFL TPO 26 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/26-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 26 Lec 3', 'TOEFL TPO 26 Official Listening Practice - Medicine', 'https://liuxue.koolearn.com/toefl/listen/26-5-q0.html', 'tpo_official', '中', 'Medicine', 300, NOW()),
('Official 26 Lec 4', 'TOEFL TPO 26 Official Listening Practice - Agriculture', 'https://liuxue.koolearn.com/toefl/listen/26-6-q0.html', 'tpo_official', '中', 'Agriculture', 300, NOW()),
('Official 27 Con 1', 'TOEFL TPO 27 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/27-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 27 Lec 1', 'TOEFL TPO 27 Official Listening Practice - Biology', 'https://liuxue.koolearn.com/toefl/listen/27-2-q0.html', 'tpo_official', '中', 'Biology', 300, NOW()),
('Official 27 Lec 2', 'TOEFL TPO 27 Official Listening Practice - Art History', 'https://liuxue.koolearn.com/toefl/listen/27-3-q0.html', 'tpo_official', '中', 'Art History', 300, NOW()),
('Official 27 Con 2', 'TOEFL TPO 27 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/27-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 27 Lec 3', 'TOEFL TPO 27 Official Listening Practice - Biology', 'https://liuxue.koolearn.com/toefl/listen/27-5-q0.html', 'tpo_official', '中', 'Biology', 300, NOW()),
('Official 27 Lec 4', 'TOEFL TPO 27 Official Listening Practice - Art History', 'https://liuxue.koolearn.com/toefl/listen/27-6-q0.html', 'tpo_official', '中', 'Art History', 300, NOW()),
('Official 28 Con 1', 'TOEFL TPO 28 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/28-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 28 Lec 1', 'TOEFL TPO 28 Official Listening Practice - Environmental Science', 'https://liuxue.koolearn.com/toefl/listen/28-2-q0.html', 'tpo_official', '中', 'Environmental Science', 300, NOW()),
('Official 28 Lec 2', 'TOEFL TPO 28 Official Listening Practice - Psychology', 'https://liuxue.koolearn.com/toefl/listen/28-3-q0.html', 'tpo_official', '中', 'Psychology', 300, NOW()),
('Official 28 Con 2', 'TOEFL TPO 28 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/28-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 28 Lec 3', 'TOEFL TPO 28 Official Listening Practice - Psychology', 'https://liuxue.koolearn.com/toefl/listen/28-5-q0.html', 'tpo_official', '中', 'Psychology', 300, NOW()),
('Official 28 Lec 4', 'TOEFL TPO 28 Official Listening Practice - Astronomy', 'https://liuxue.koolearn.com/toefl/listen/28-6-q0.html', 'tpo_official', '中', 'Astronomy', 300, NOW()),
('Official 29 Con 1', 'TOEFL TPO 29 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/29-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 29 Lec 1', 'TOEFL TPO 29 Official Listening Practice - Astronomy', 'https://liuxue.koolearn.com/toefl/listen/29-2-q0.html', 'tpo_official', '中', 'Astronomy', 300, NOW()),
('Official 29 Lec 2', 'TOEFL TPO 29 Official Listening Practice - Archaeology', 'https://liuxue.koolearn.com/toefl/listen/29-3-q0.html', 'tpo_official', '中', 'Archaeology', 300, NOW()),
('Official 29 Con 2', 'TOEFL TPO 29 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/29-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 29 Lec 3', 'TOEFL TPO 29 Official Listening Practice - Chemistry', 'https://liuxue.koolearn.com/toefl/listen/29-5-q0.html', 'tpo_official', '中', 'Chemistry', 300, NOW()),
('Official 29 Lec 4', 'TOEFL TPO 29 Official Listening Practice - Music', 'https://liuxue.koolearn.com/toefl/listen/29-6-q0.html', 'tpo_official', '中', 'Music', 300, NOW()),
('Official 30 Con 1', 'TOEFL TPO 30 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/30-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 30 Lec 1', 'TOEFL TPO 30 Official Listening Practice - Chemistry', 'https://liuxue.koolearn.com/toefl/listen/30-2-q0.html', 'tpo_official', '中', 'Chemistry', 300, NOW()),
('Official 30 Lec 2', 'TOEFL TPO 30 Official Listening Practice - Music', 'https://liuxue.koolearn.com/toefl/listen/30-3-q0.html', 'tpo_official', '中', 'Music', 300, NOW()),
('Official 30 Con 2', 'TOEFL TPO 30 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/30-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 30 Lec 3', 'TOEFL TPO 30 Official Listening Practice - Philosophy', 'https://liuxue.koolearn.com/toefl/listen/30-5-q0.html', 'tpo_official', '中', 'Philosophy', 300, NOW()),
('Official 30 Lec 4', 'TOEFL TPO 30 Official Listening Practice - Anthropology', 'https://liuxue.koolearn.com/toefl/listen/30-6-q0.html', 'tpo_official', '中', 'Anthropology', 300, NOW()),
('Official 31 Con 1', 'TOEFL TPO 31 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/31-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 31 Lec 1', 'TOEFL TPO 31 Official Listening Practice - Literature', 'https://liuxue.koolearn.com/toefl/listen/31-2-q0.html', 'tpo_official', '中', 'Literature', 300, NOW()),
('Official 31 Lec 2', 'TOEFL TPO 31 Official Listening Practice - Philosophy', 'https://liuxue.koolearn.com/toefl/listen/31-3-q0.html', 'tpo_official', '中', 'Philosophy', 300, NOW()),
('Official 31 Con 2', 'TOEFL TPO 31 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/31-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 31 Lec 3', 'TOEFL TPO 31 Official Listening Practice - Business', 'https://liuxue.koolearn.com/toefl/listen/31-5-q0.html', 'tpo_official', '中', 'Business', 300, NOW()),
('Official 31 Lec 4', 'TOEFL TPO 31 Official Listening Practice - History', 'https://liuxue.koolearn.com/toefl/listen/31-6-q0.html', 'tpo_official', '中', 'History', 300, NOW()),
('Official 32 Con 1', 'TOEFL TPO 32 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/32-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 32 Lec 1', 'TOEFL TPO 32 Official Listening Practice - Anthropology', 'https://liuxue.koolearn.com/toefl/listen/32-2-q0.html', 'tpo_official', '中', 'Anthropology', 300, NOW()),
('Official 32 Lec 2', 'TOEFL TPO 32 Official Listening Practice - Geology', 'https://liuxue.koolearn.com/toefl/listen/32-3-q0.html', 'tpo_official', '中', 'Geology', 300, NOW()),
('Official 32 Con 2', 'TOEFL TPO 32 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/32-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 32 Lec 3', 'TOEFL TPO 32 Official Listening Practice - Physics', 'https://liuxue.koolearn.com/toefl/listen/32-5-q0.html', 'tpo_official', '中', 'Physics', 300, NOW()),
('Official 32 Lec 4', 'TOEFL TPO 32 Official Listening Practice - Sociology', 'https://liuxue.koolearn.com/toefl/listen/32-6-q0.html', 'tpo_official', '中', 'Sociology', 300, NOW()),
('Official 33 Con 1', 'TOEFL TPO 33 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/33-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 33 Lec 1', 'TOEFL TPO 33 Official Listening Practice - Business', 'https://liuxue.koolearn.com/toefl/listen/33-2-q0.html', 'tpo_official', '中', 'Business', 300, NOW()),
('Official 33 Lec 2', 'TOEFL TPO 33 Official Listening Practice - History', 'https://liuxue.koolearn.com/toefl/listen/33-3-q0.html', 'tpo_official', '中', 'History', 300, NOW()),
('Official 33 Con 2', 'TOEFL TPO 33 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/33-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 33 Lec 3', 'TOEFL TPO 33 Official Listening Practice - Economics', 'https://liuxue.koolearn.com/toefl/listen/33-5-q0.html', 'tpo_official', '中', 'Economics', 300, NOW()),
('Official 33 Lec 4', 'TOEFL TPO 33 Official Listening Practice - Architecture', 'https://liuxue.koolearn.com/toefl/listen/33-6-q0.html', 'tpo_official', '中', 'Architecture', 300, NOW()),
('Official 34 Con 1', 'TOEFL TPO 34 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/34-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 34 Lec 1', 'TOEFL TPO 34 Official Listening Practice - Engineering', 'https://liuxue.koolearn.com/toefl/listen/34-2-q0.html', 'tpo_official', '中', 'Engineering', 300, NOW()),
('Official 34 Lec 2', 'TOEFL TPO 34 Official Listening Practice - Physics', 'https://liuxue.koolearn.com/toefl/listen/34-3-q0.html', 'tpo_official', '中', 'Physics', 300, NOW()),
('Official 34 Con 2', 'TOEFL TPO 34 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/34-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 34 Lec 3', 'TOEFL TPO 34 Official Listening Practice - Political Science', 'https://liuxue.koolearn.com/toefl/listen/34-5-q0.html', 'tpo_official', '中', 'Political Science', 300, NOW()),
('Official 34 Lec 4', 'TOEFL TPO 34 Official Listening Practice - Mathematics', 'https://liuxue.koolearn.com/toefl/listen/34-6-q0.html', 'tpo_official', '中', 'Mathematics', 300, NOW()),
('Official 35 Con 1', 'TOEFL TPO 35 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/35-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 35 Lec 1', 'TOEFL TPO 35 Official Listening Practice - Sociology', 'https://liuxue.koolearn.com/toefl/listen/35-2-q0.html', 'tpo_official', '中', 'Sociology', 300, NOW()),
('Official 35 Lec 2', 'TOEFL TPO 35 Official Listening Practice - Linguistics', 'https://liuxue.koolearn.com/toefl/listen/35-3-q0.html', 'tpo_official', '中', 'Linguistics', 300, NOW()),
('Official 35 Con 2', 'TOEFL TPO 35 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/35-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 35 Lec 3', 'TOEFL TPO 35 Official Listening Practice - Medicine', 'https://liuxue.koolearn.com/toefl/listen/35-5-q0.html', 'tpo_official', '中', 'Medicine', 300, NOW()),
('Official 35 Lec 4', 'TOEFL TPO 35 Official Listening Practice - Agriculture', 'https://liuxue.koolearn.com/toefl/listen/35-6-q0.html', 'tpo_official', '中', 'Agriculture', 300, NOW()),
('Official 36 Con 1', 'TOEFL TPO 36 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/36-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 36 Lec 1', 'TOEFL TPO 36 Official Listening Practice - Economics', 'https://liuxue.koolearn.com/toefl/listen/36-2-q0.html', 'tpo_official', '中', 'Economics', 300, NOW()),
('Official 36 Lec 2', 'TOEFL TPO 36 Official Listening Practice - Architecture', 'https://liuxue.koolearn.com/toefl/listen/36-3-q0.html', 'tpo_official', '中', 'Architecture', 300, NOW()),
('Official 36 Con 2', 'TOEFL TPO 36 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/36-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 36 Lec 3', 'TOEFL TPO 36 Official Listening Practice - Biology', 'https://liuxue.koolearn.com/toefl/listen/36-5-q0.html', 'tpo_official', '中', 'Biology', 300, NOW()),
('Official 36 Lec 4', 'TOEFL TPO 36 Official Listening Practice - Art History', 'https://liuxue.koolearn.com/toefl/listen/36-6-q0.html', 'tpo_official', '中', 'Art History', 300, NOW()),
('Official 37 Con 1', 'TOEFL TPO 37 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/37-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 37 Lec 1', 'TOEFL TPO 37 Official Listening Practice - Geography', 'https://liuxue.koolearn.com/toefl/listen/37-2-q0.html', 'tpo_official', '中', 'Geography', 300, NOW()),
('Official 37 Lec 2', 'TOEFL TPO 37 Official Listening Practice - Political Science', 'https://liuxue.koolearn.com/toefl/listen/37-3-q0.html', 'tpo_official', '中', 'Political Science', 300, NOW()),
('Official 37 Con 2', 'TOEFL TPO 37 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/37-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 37 Lec 3', 'TOEFL TPO 37 Official Listening Practice - Psychology', 'https://liuxue.koolearn.com/toefl/listen/37-5-q0.html', 'tpo_official', '中', 'Psychology', 300, NOW()),
('Official 37 Lec 4', 'TOEFL TPO 37 Official Listening Practice - Astronomy', 'https://liuxue.koolearn.com/toefl/listen/37-6-q0.html', 'tpo_official', '中', 'Astronomy', 300, NOW()),
('Official 38 Con 1', 'TOEFL TPO 38 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/38-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 38 Lec 1', 'TOEFL TPO 38 Official Listening Practice - Mathematics', 'https://liuxue.koolearn.com/toefl/listen/38-2-q0.html', 'tpo_official', '中', 'Mathematics', 300, NOW()),
('Official 38 Lec 2', 'TOEFL TPO 38 Official Listening Practice - Computer Science', 'https://liuxue.koolearn.com/toefl/listen/38-3-q0.html', 'tpo_official', '中', 'Computer Science', 300, NOW()),
('Official 38 Con 2', 'TOEFL TPO 38 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/38-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 38 Lec 3', 'TOEFL TPO 38 Official Listening Practice - Chemistry', 'https://liuxue.koolearn.com/toefl/listen/38-5-q0.html', 'tpo_official', '中', 'Chemistry', 300, NOW()),
('Official 38 Lec 4', 'TOEFL TPO 38 Official Listening Practice - Music', 'https://liuxue.koolearn.com/toefl/listen/38-6-q0.html', 'tpo_official', '中', 'Music', 300, NOW()),
('Official 39 Con 1', 'TOEFL TPO 39 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/39-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 39 Lec 1', 'TOEFL TPO 39 Official Listening Practice - Medicine', 'https://liuxue.koolearn.com/toefl/listen/39-2-q0.html', 'tpo_official', '中', 'Medicine', 300, NOW()),
('Official 39 Lec 2', 'TOEFL TPO 39 Official Listening Practice - Agriculture', 'https://liuxue.koolearn.com/toefl/listen/39-3-q0.html', 'tpo_official', '中', 'Agriculture', 300, NOW()),
('Official 39 Con 2', 'TOEFL TPO 39 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/39-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 39 Lec 3', 'TOEFL TPO 39 Official Listening Practice - Philosophy', 'https://liuxue.koolearn.com/toefl/listen/39-5-q0.html', 'tpo_official', '中', 'Philosophy', 300, NOW()),
('Official 39 Lec 4', 'TOEFL TPO 39 Official Listening Practice - Anthropology', 'https://liuxue.koolearn.com/toefl/listen/39-6-q0.html', 'tpo_official', '中', 'Anthropology', 300, NOW()),
('Official 40 Con 1', 'TOEFL TPO 40 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/40-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 40 Lec 1', 'TOEFL TPO 40 Official Listening Practice - Journalism', 'https://liuxue.koolearn.com/toefl/listen/40-2-q0.html', 'tpo_official', '中', 'Journalism', 300, NOW()),
('Official 40 Lec 2', 'TOEFL TPO 40 Official Listening Practice - Biology', 'https://liuxue.koolearn.com/toefl/listen/40-3-q0.html', 'tpo_official', '中', 'Biology', 300, NOW()),
('Official 40 Con 2', 'TOEFL TPO 40 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/40-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 40 Lec 3', 'TOEFL TPO 40 Official Listening Practice - Business', 'https://liuxue.koolearn.com/toefl/listen/40-5-q0.html', 'tpo_official', '中', 'Business', 300, NOW()),
('Official 40 Lec 4', 'TOEFL TPO 40 Official Listening Practice - History', 'https://liuxue.koolearn.com/toefl/listen/40-6-q0.html', 'tpo_official', '中', 'History', 300, NOW()),
('Official 41 Con 1', 'TOEFL TPO 41 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/41-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 41 Lec 1', 'TOEFL TPO 41 Official Listening Practice - Art History', 'https://liuxue.koolearn.com/toefl/listen/41-2-q0.html', 'tpo_official', '中', 'Art History', 300, NOW()),
('Official 41 Lec 2', 'TOEFL TPO 41 Official Listening Practice - Environmental Science', 'https://liuxue.koolearn.com/toefl/listen/41-3-q0.html', 'tpo_official', '中', 'Environmental Science', 300, NOW()),
('Official 41 Con 2', 'TOEFL TPO 41 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/41-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 41 Lec 3', 'TOEFL TPO 41 Official Listening Practice - Physics', 'https://liuxue.koolearn.com/toefl/listen/41-5-q0.html', 'tpo_official', '中', 'Physics', 300, NOW()),
('Official 41 Lec 4', 'TOEFL TPO 41 Official Listening Practice - Sociology', 'https://liuxue.koolearn.com/toefl/listen/41-6-q0.html', 'tpo_official', '中', 'Sociology', 300, NOW()),
('Official 42 Con 1', 'TOEFL TPO 42 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/42-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 42 Lec 1', 'TOEFL TPO 42 Official Listening Practice - Psychology', 'https://liuxue.koolearn.com/toefl/listen/42-2-q0.html', 'tpo_official', '中', 'Psychology', 300, NOW()),
('Official 42 Lec 2', 'TOEFL TPO 42 Official Listening Practice - Astronomy', 'https://liuxue.koolearn.com/toefl/listen/42-3-q0.html', 'tpo_official', '中', 'Astronomy', 300, NOW()),
('Official 42 Con 2', 'TOEFL TPO 42 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/42-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 42 Lec 3', 'TOEFL TPO 42 Official Listening Practice - Economics', 'https://liuxue.koolearn.com/toefl/listen/42-5-q0.html', 'tpo_official', '中', 'Economics', 300, NOW()),
('Official 42 Lec 4', 'TOEFL TPO 42 Official Listening Practice - Architecture', 'https://liuxue.koolearn.com/toefl/listen/42-6-q0.html', 'tpo_official', '中', 'Architecture', 300, NOW()),
('Official 43 Con 1', 'TOEFL TPO 43 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/43-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 43 Lec 1', 'TOEFL TPO 43 Official Listening Practice - Archaeology', 'https://liuxue.koolearn.com/toefl/listen/43-2-q0.html', 'tpo_official', '中', 'Archaeology', 300, NOW()),
('Official 43 Lec 2', 'TOEFL TPO 43 Official Listening Practice - Chemistry', 'https://liuxue.koolearn.com/toefl/listen/43-3-q0.html', 'tpo_official', '中', 'Chemistry', 300, NOW()),
('Official 43 Con 2', 'TOEFL TPO 43 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/43-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 43 Lec 3', 'TOEFL TPO 43 Official Listening Practice - Political Science', 'https://liuxue.koolearn.com/toefl/listen/43-5-q0.html', 'tpo_official', '中', 'Political Science', 300, NOW()),
('Official 43 Lec 4', 'TOEFL TPO 43 Official Listening Practice - Mathematics', 'https://liuxue.koolearn.com/toefl/listen/43-6-q0.html', 'tpo_official', '中', 'Mathematics', 300, NOW()),
('Official 44 Con 1', 'TOEFL TPO 44 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/44-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 44 Lec 1', 'TOEFL TPO 44 Official Listening Practice - Music', 'https://liuxue.koolearn.com/toefl/listen/44-2-q0.html', 'tpo_official', '中', 'Music', 300, NOW()),
('Official 44 Lec 2', 'TOEFL TPO 44 Official Listening Practice - Literature', 'https://liuxue.koolearn.com/toefl/listen/44-3-q0.html', 'tpo_official', '中', 'Literature', 300, NOW()),
('Official 44 Con 2', 'TOEFL TPO 44 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/44-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 44 Lec 3', 'TOEFL TPO 44 Official Listening Practice - Medicine', 'https://liuxue.koolearn.com/toefl/listen/44-5-q0.html', 'tpo_official', '中', 'Medicine', 300, NOW()),
('Official 44 Lec 4', 'TOEFL TPO 44 Official Listening Practice - Agriculture', 'https://liuxue.koolearn.com/toefl/listen/44-6-q0.html', 'tpo_official', '中', 'Agriculture', 300, NOW()),
('Official 45 Con 1', 'TOEFL TPO 45 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/45-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 45 Lec 1', 'TOEFL TPO 45 Official Listening Practice - Philosophy', 'https://liuxue.koolearn.com/toefl/listen/45-2-q0.html', 'tpo_official', '中', 'Philosophy', 300, NOW()),
('Official 45 Lec 2', 'TOEFL TPO 45 Official Listening Practice - Anthropology', 'https://liuxue.koolearn.com/toefl/listen/45-3-q0.html', 'tpo_official', '中', 'Anthropology', 300, NOW()),
('Official 45 Con 2', 'TOEFL TPO 45 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/45-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 45 Lec 3', 'TOEFL TPO 45 Official Listening Practice - Biology', 'https://liuxue.koolearn.com/toefl/listen/45-5-q0.html', 'tpo_official', '中', 'Biology', 300, NOW()),
('Official 45 Lec 4', 'TOEFL TPO 45 Official Listening Practice - Art History', 'https://liuxue.koolearn.com/toefl/listen/45-6-q0.html', 'tpo_official', '中', 'Art History', 300, NOW()),
('Official 46 Con 1', 'TOEFL TPO 46 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/46-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 46 Lec 1', 'TOEFL TPO 46 Official Listening Practice - Geology', 'https://liuxue.koolearn.com/toefl/listen/46-2-q0.html', 'tpo_official', '中', 'Geology', 300, NOW()),
('Official 46 Lec 2', 'TOEFL TPO 46 Official Listening Practice - Business', 'https://liuxue.koolearn.com/toefl/listen/46-3-q0.html', 'tpo_official', '中', 'Business', 300, NOW()),
('Official 46 Con 2', 'TOEFL TPO 46 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/46-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 46 Lec 3', 'TOEFL TPO 46 Official Listening Practice - Psychology', 'https://liuxue.koolearn.com/toefl/listen/46-5-q0.html', 'tpo_official', '中', 'Psychology', 300, NOW()),
('Official 46 Lec 4', 'TOEFL TPO 46 Official Listening Practice - Astronomy', 'https://liuxue.koolearn.com/toefl/listen/46-6-q0.html', 'tpo_official', '中', 'Astronomy', 300, NOW()),
('Official 47 Con 1', 'TOEFL TPO 47 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/47-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 47 Lec 1', 'TOEFL TPO 47 Official Listening Practice - History', 'https://liuxue.koolearn.com/toefl/listen/47-2-q0.html', 'tpo_official', '中', 'History', 300, NOW()),
('Official 47 Lec 2', 'TOEFL TPO 47 Official Listening Practice - Engineering', 'https://liuxue.koolearn.com/toefl/listen/47-3-q0.html', 'tpo_official', '中', 'Engineering', 300, NOW()),
('Official 47 Con 2', 'TOEFL TPO 47 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/47-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 47 Lec 3', 'TOEFL TPO 47 Official Listening Practice - Chemistry', 'https://liuxue.koolearn.com/toefl/listen/47-5-q0.html', 'tpo_official', '中', 'Chemistry', 300, NOW()),
('Official 47 Lec 4', 'TOEFL TPO 47 Official Listening Practice - Music', 'https://liuxue.koolearn.com/toefl/listen/47-6-q0.html', 'tpo_official', '中', 'Music', 300, NOW()),
('Official 48 Con 1', 'TOEFL TPO 48 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/48-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 48 Lec 1', 'TOEFL TPO 48 Official Listening Practice - Physics', 'https://liuxue.koolearn.com/toefl/listen/48-2-q0.html', 'tpo_official', '中', 'Physics', 300, NOW()),
('Official 48 Lec 2', 'TOEFL TPO 48 Official Listening Practice - Sociology', 'https://liuxue.koolearn.com/toefl/listen/48-3-q0.html', 'tpo_official', '中', 'Sociology', 300, NOW()),
('Official 48 Con 2', 'TOEFL TPO 48 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/48-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 48 Lec 3', 'TOEFL TPO 48 Official Listening Practice - Philosophy', 'https://liuxue.koolearn.com/toefl/listen/48-5-q0.html', 'tpo_official', '中', 'Philosophy', 300, NOW()),
('Official 48 Lec 4', 'TOEFL TPO 48 Official Listening Practice - Anthropology', 'https://liuxue.koolearn.com/toefl/listen/48-6-q0.html', 'tpo_official', '中', 'Anthropology', 300, NOW()),
('Official 49 Con 1', 'TOEFL TPO 49 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/49-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 49 Lec 1', 'TOEFL TPO 49 Official Listening Practice - Linguistics', 'https://liuxue.koolearn.com/toefl/listen/49-2-q0.html', 'tpo_official', '中', 'Linguistics', 300, NOW()),
('Official 49 Lec 2', 'TOEFL TPO 49 Official Listening Practice - Economics', 'https://liuxue.koolearn.com/toefl/listen/49-3-q0.html', 'tpo_official', '中', 'Economics', 300, NOW()),
('Official 49 Con 2', 'TOEFL TPO 49 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/49-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 49 Lec 3', 'TOEFL TPO 49 Official Listening Practice - Business', 'https://liuxue.koolearn.com/toefl/listen/49-5-q0.html', 'tpo_official', '中', 'Business', 300, NOW()),
('Official 49 Lec 4', 'TOEFL TPO 49 Official Listening Practice - History', 'https://liuxue.koolearn.com/toefl/listen/49-6-q0.html', 'tpo_official', '中', 'History', 300, NOW()),
('Official 50 Con 1', 'TOEFL TPO 50 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/50-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 50 Lec 1', 'TOEFL TPO 50 Official Listening Practice - Architecture', 'https://liuxue.koolearn.com/toefl/listen/50-2-q0.html', 'tpo_official', '中', 'Architecture', 300, NOW()),
('Official 50 Lec 2', 'TOEFL TPO 50 Official Listening Practice - Geography', 'https://liuxue.koolearn.com/toefl/listen/50-3-q0.html', 'tpo_official', '中', 'Geography', 300, NOW()),
('Official 50 Con 2', 'TOEFL TPO 50 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/50-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 50 Lec 3', 'TOEFL TPO 50 Official Listening Practice - Physics', 'https://liuxue.koolearn.com/toefl/listen/50-5-q0.html', 'tpo_official', '中', 'Physics', 300, NOW()),
('Official 50 Lec 4', 'TOEFL TPO 50 Official Listening Practice - Sociology', 'https://liuxue.koolearn.com/toefl/listen/50-6-q0.html', 'tpo_official', '中', 'Sociology', 300, NOW()),
('Official 51 Con 1', 'TOEFL TPO 51 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/51-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 51 Lec 1', 'TOEFL TPO 51 Official Listening Practice - Political Science', 'https://liuxue.koolearn.com/toefl/listen/51-2-q0.html', 'tpo_official', '中', 'Political Science', 300, NOW()),
('Official 51 Lec 2', 'TOEFL TPO 51 Official Listening Practice - Mathematics', 'https://liuxue.koolearn.com/toefl/listen/51-3-q0.html', 'tpo_official', '中', 'Mathematics', 300, NOW()),
('Official 51 Con 2', 'TOEFL TPO 51 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/51-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 51 Lec 3', 'TOEFL TPO 51 Official Listening Practice - Economics', 'https://liuxue.koolearn.com/toefl/listen/51-5-q0.html', 'tpo_official', '中', 'Economics', 300, NOW()),
('Official 51 Lec 4', 'TOEFL TPO 51 Official Listening Practice - Architecture', 'https://liuxue.koolearn.com/toefl/listen/51-6-q0.html', 'tpo_official', '中', 'Architecture', 300, NOW()),
('Official 52 Con 1', 'TOEFL TPO 52 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/52-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 52 Lec 1', 'TOEFL TPO 52 Official Listening Practice - Computer Science', 'https://liuxue.koolearn.com/toefl/listen/52-2-q0.html', 'tpo_official', '中', 'Computer Science', 300, NOW()),
('Official 52 Lec 2', 'TOEFL TPO 52 Official Listening Practice - Medicine', 'https://liuxue.koolearn.com/toefl/listen/52-3-q0.html', 'tpo_official', '中', 'Medicine', 300, NOW()),
('Official 52 Con 2', 'TOEFL TPO 52 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/52-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 52 Lec 3', 'TOEFL TPO 52 Official Listening Practice - Political Science', 'https://liuxue.koolearn.com/toefl/listen/52-5-q0.html', 'tpo_official', '中', 'Political Science', 300, NOW()),
('Official 52 Lec 4', 'TOEFL TPO 52 Official Listening Practice - Mathematics', 'https://liuxue.koolearn.com/toefl/listen/52-6-q0.html', 'tpo_official', '中', 'Mathematics', 300, NOW()),
('Official 53 Con 1', 'TOEFL TPO 53 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/53-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 53 Lec 1', 'TOEFL TPO 53 Official Listening Practice - Agriculture', 'https://liuxue.koolearn.com/toefl/listen/53-2-q0.html', 'tpo_official', '中', 'Agriculture', 300, NOW()),
('Official 53 Lec 2', 'TOEFL TPO 53 Official Listening Practice - Journalism', 'https://liuxue.koolearn.com/toefl/listen/53-3-q0.html', 'tpo_official', '中', 'Journalism', 300, NOW()),
('Official 53 Con 2', 'TOEFL TPO 53 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/53-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 53 Lec 3', 'TOEFL TPO 53 Official Listening Practice - Medicine', 'https://liuxue.koolearn.com/toefl/listen/53-5-q0.html', 'tpo_official', '中', 'Medicine', 300, NOW()),
('Official 53 Lec 4', 'TOEFL TPO 53 Official Listening Practice - Agriculture', 'https://liuxue.koolearn.com/toefl/listen/53-6-q0.html', 'tpo_official', '中', 'Agriculture', 300, NOW()),
('Official 54 Con 1', 'TOEFL TPO 54 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/54-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 54 Lec 1', 'TOEFL TPO 54 Official Listening Practice - Biology', 'https://liuxue.koolearn.com/toefl/listen/54-2-q0.html', 'tpo_official', '中', 'Biology', 300, NOW()),
('Official 54 Lec 2', 'TOEFL TPO 54 Official Listening Practice - Art History', 'https://liuxue.koolearn.com/toefl/listen/54-3-q0.html', 'tpo_official', '中', 'Art History', 300, NOW()),
('Official 54 Con 2', 'TOEFL TPO 54 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/54-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 54 Lec 3', 'TOEFL TPO 54 Official Listening Practice - Biology', 'https://liuxue.koolearn.com/toefl/listen/54-5-q0.html', 'tpo_official', '中', 'Biology', 300, NOW()),
('Official 54 Lec 4', 'TOEFL TPO 54 Official Listening Practice - Art History', 'https://liuxue.koolearn.com/toefl/listen/54-6-q0.html', 'tpo_official', '中', 'Art History', 300, NOW()),
('Official 55 Con 1', 'TOEFL TPO 55 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/55-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 55 Lec 1', 'TOEFL TPO 55 Official Listening Practice - Environmental Science', 'https://liuxue.koolearn.com/toefl/listen/55-2-q0.html', 'tpo_official', '中', 'Environmental Science', 300, NOW()),
('Official 55 Lec 2', 'TOEFL TPO 55 Official Listening Practice - Psychology', 'https://liuxue.koolearn.com/toefl/listen/55-3-q0.html', 'tpo_official', '中', 'Psychology', 300, NOW()),
('Official 55 Con 2', 'TOEFL TPO 55 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/55-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 55 Lec 3', 'TOEFL TPO 55 Official Listening Practice - Psychology', 'https://liuxue.koolearn.com/toefl/listen/55-5-q0.html', 'tpo_official', '中', 'Psychology', 300, NOW()),
('Official 55 Lec 4', 'TOEFL TPO 55 Official Listening Practice - Astronomy', 'https://liuxue.koolearn.com/toefl/listen/55-6-q0.html', 'tpo_official', '中', 'Astronomy', 300, NOW()),
('Official 56 Con 1', 'TOEFL TPO 56 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/56-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 56 Lec 1', 'TOEFL TPO 56 Official Listening Practice - Astronomy', 'https://liuxue.koolearn.com/toefl/listen/56-2-q0.html', 'tpo_official', '中', 'Astronomy', 300, NOW()),
('Official 56 Lec 2', 'TOEFL TPO 56 Official Listening Practice - Archaeology', 'https://liuxue.koolearn.com/toefl/listen/56-3-q0.html', 'tpo_official', '中', 'Archaeology', 300, NOW()),
('Official 56 Con 2', 'TOEFL TPO 56 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/56-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 56 Lec 3', 'TOEFL TPO 56 Official Listening Practice - Chemistry', 'https://liuxue.koolearn.com/toefl/listen/56-5-q0.html', 'tpo_official', '中', 'Chemistry', 300, NOW()),
('Official 56 Lec 4', 'TOEFL TPO 56 Official Listening Practice - Music', 'https://liuxue.koolearn.com/toefl/listen/56-6-q0.html', 'tpo_official', '中', 'Music', 300, NOW()),
('Official 57 Con 1', 'TOEFL TPO 57 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/57-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 57 Lec 1', 'TOEFL TPO 57 Official Listening Practice - Chemistry', 'https://liuxue.koolearn.com/toefl/listen/57-2-q0.html', 'tpo_official', '中', 'Chemistry', 300, NOW()),
('Official 57 Lec 2', 'TOEFL TPO 57 Official Listening Practice - Music', 'https://liuxue.koolearn.com/toefl/listen/57-3-q0.html', 'tpo_official', '中', 'Music', 300, NOW()),
('Official 57 Con 2', 'TOEFL TPO 57 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/57-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 57 Lec 3', 'TOEFL TPO 57 Official Listening Practice - Philosophy', 'https://liuxue.koolearn.com/toefl/listen/57-5-q0.html', 'tpo_official', '中', 'Philosophy', 300, NOW()),
('Official 57 Lec 4', 'TOEFL TPO 57 Official Listening Practice - Anthropology', 'https://liuxue.koolearn.com/toefl/listen/57-6-q0.html', 'tpo_official', '中', 'Anthropology', 300, NOW()),
('Official 58 Con 1', 'TOEFL TPO 58 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/58-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 58 Lec 1', 'TOEFL TPO 58 Official Listening Practice - Literature', 'https://liuxue.koolearn.com/toefl/listen/58-2-q0.html', 'tpo_official', '中', 'Literature', 300, NOW()),
('Official 58 Lec 2', 'TOEFL TPO 58 Official Listening Practice - Philosophy', 'https://liuxue.koolearn.com/toefl/listen/58-3-q0.html', 'tpo_official', '中', 'Philosophy', 300, NOW()),
('Official 58 Con 2', 'TOEFL TPO 58 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/58-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 58 Lec 3', 'TOEFL TPO 58 Official Listening Practice - Business', 'https://liuxue.koolearn.com/toefl/listen/58-5-q0.html', 'tpo_official', '中', 'Business', 300, NOW()),
('Official 58 Lec 4', 'TOEFL TPO 58 Official Listening Practice - History', 'https://liuxue.koolearn.com/toefl/listen/58-6-q0.html', 'tpo_official', '中', 'History', 300, NOW()),
('Official 59 Con 1', 'TOEFL TPO 59 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/59-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 59 Lec 1', 'TOEFL TPO 59 Official Listening Practice - Anthropology', 'https://liuxue.koolearn.com/toefl/listen/59-2-q0.html', 'tpo_official', '中', 'Anthropology', 300, NOW()),
('Official 59 Lec 2', 'TOEFL TPO 59 Official Listening Practice - Geology', 'https://liuxue.koolearn.com/toefl/listen/59-3-q0.html', 'tpo_official', '中', 'Geology', 300, NOW()),
('Official 59 Con 2', 'TOEFL TPO 59 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/59-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 59 Lec 3', 'TOEFL TPO 59 Official Listening Practice - Physics', 'https://liuxue.koolearn.com/toefl/listen/59-5-q0.html', 'tpo_official', '中', 'Physics', 300, NOW()),
('Official 59 Lec 4', 'TOEFL TPO 59 Official Listening Practice - Sociology', 'https://liuxue.koolearn.com/toefl/listen/59-6-q0.html', 'tpo_official', '中', 'Sociology', 300, NOW()),
('Official 60 Con 1', 'TOEFL TPO 60 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/60-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 60 Lec 1', 'TOEFL TPO 60 Official Listening Practice - Business', 'https://liuxue.koolearn.com/toefl/listen/60-2-q0.html', 'tpo_official', '中', 'Business', 300, NOW()),
('Official 60 Lec 2', 'TOEFL TPO 60 Official Listening Practice - History', 'https://liuxue.koolearn.com/toefl/listen/60-3-q0.html', 'tpo_official', '中', 'History', 300, NOW()),
('Official 60 Con 2', 'TOEFL TPO 60 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/60-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 60 Lec 3', 'TOEFL TPO 60 Official Listening Practice - Economics', 'https://liuxue.koolearn.com/toefl/listen/60-5-q0.html', 'tpo_official', '中', 'Economics', 300, NOW()),
('Official 60 Lec 4', 'TOEFL TPO 60 Official Listening Practice - Architecture', 'https://liuxue.koolearn.com/toefl/listen/60-6-q0.html', 'tpo_official', '中', 'Architecture', 300, NOW()),
('Official 61 Con 1', 'TOEFL TPO 61 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/61-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 61 Lec 1', 'TOEFL TPO 61 Official Listening Practice - Engineering', 'https://liuxue.koolearn.com/toefl/listen/61-2-q0.html', 'tpo_official', '中', 'Engineering', 300, NOW()),
('Official 61 Lec 2', 'TOEFL TPO 61 Official Listening Practice - Physics', 'https://liuxue.koolearn.com/toefl/listen/61-3-q0.html', 'tpo_official', '中', 'Physics', 300, NOW()),
('Official 61 Con 2', 'TOEFL TPO 61 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/61-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 61 Lec 3', 'TOEFL TPO 61 Official Listening Practice - Political Science', 'https://liuxue.koolearn.com/toefl/listen/61-5-q0.html', 'tpo_official', '中', 'Political Science', 300, NOW()),
('Official 61 Lec 4', 'TOEFL TPO 61 Official Listening Practice - Mathematics', 'https://liuxue.koolearn.com/toefl/listen/61-6-q0.html', 'tpo_official', '中', 'Mathematics', 300, NOW()),
('Official 62 Con 1', 'TOEFL TPO 62 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/62-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 62 Lec 1', 'TOEFL TPO 62 Official Listening Practice - Sociology', 'https://liuxue.koolearn.com/toefl/listen/62-2-q0.html', 'tpo_official', '中', 'Sociology', 300, NOW()),
('Official 62 Lec 2', 'TOEFL TPO 62 Official Listening Practice - Linguistics', 'https://liuxue.koolearn.com/toefl/listen/62-3-q0.html', 'tpo_official', '中', 'Linguistics', 300, NOW()),
('Official 62 Con 2', 'TOEFL TPO 62 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/62-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 62 Lec 3', 'TOEFL TPO 62 Official Listening Practice - Medicine', 'https://liuxue.koolearn.com/toefl/listen/62-5-q0.html', 'tpo_official', '中', 'Medicine', 300, NOW()),
('Official 62 Lec 4', 'TOEFL TPO 62 Official Listening Practice - Agriculture', 'https://liuxue.koolearn.com/toefl/listen/62-6-q0.html', 'tpo_official', '中', 'Agriculture', 300, NOW()),
('Official 63 Con 1', 'TOEFL TPO 63 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/63-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 63 Lec 1', 'TOEFL TPO 63 Official Listening Practice - Economics', 'https://liuxue.koolearn.com/toefl/listen/63-2-q0.html', 'tpo_official', '中', 'Economics', 300, NOW()),
('Official 63 Lec 2', 'TOEFL TPO 63 Official Listening Practice - Architecture', 'https://liuxue.koolearn.com/toefl/listen/63-3-q0.html', 'tpo_official', '中', 'Architecture', 300, NOW()),
('Official 63 Con 2', 'TOEFL TPO 63 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/63-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 63 Lec 3', 'TOEFL TPO 63 Official Listening Practice - Biology', 'https://liuxue.koolearn.com/toefl/listen/63-5-q0.html', 'tpo_official', '中', 'Biology', 300, NOW()),
('Official 63 Lec 4', 'TOEFL TPO 63 Official Listening Practice - Art History', 'https://liuxue.koolearn.com/toefl/listen/63-6-q0.html', 'tpo_official', '中', 'Art History', 300, NOW()),
('Official 64 Con 1', 'TOEFL TPO 64 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/64-1-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 64 Lec 1', 'TOEFL TPO 64 Official Listening Practice - Geography', 'https://liuxue.koolearn.com/toefl/listen/64-2-q0.html', 'tpo_official', '中', 'Geography', 300, NOW()),
('Official 64 Lec 2', 'TOEFL TPO 64 Official Listening Practice - Political Science', 'https://liuxue.koolearn.com/toefl/listen/64-3-q0.html', 'tpo_official', '中', 'Political Science', 300, NOW()),
('Official 64 Con 2', 'TOEFL TPO 64 Official Listening Practice - Student-Teacher Conversation', 'https://liuxue.koolearn.com/toefl/listen/64-4-q0.html', 'tpo_official', '中', 'Student-Teacher Conversation', 300, NOW()),
('Official 64 Lec 3', 'TOEFL TPO 64 Official Listening Practice - Psychology', 'https://liuxue.koolearn.com/toefl/listen/64-5-q0.html', 'tpo_official', '中', 'Psychology', 300, NOW()),
('Official 64 Lec 4', 'TOEFL TPO 64 Official Listening Practice - Astronomy', 'https://liuxue.koolearn.com/toefl/listen/64-6-q0.html', 'tpo_official', '中', 'Astronomy', 300, NOW());